### PR TITLE
fix: Client authentication

### PR DESCRIPTION
**Pull request by GTB3NW**
Side-imports auth package instead of oidc specifically. Should resolve https://github.com/profefe/kube-profefe/issues/33 and other similar issues.

The vendor folder has also been updated. Might I suggest removing that since go modules makes it redundant and vendor folder commits are noisy :(

### CODE REVIEW

**Comment by GTB3NW** [comment]
@gianarb Ready for review :)

**Comment by gianarb** [comment]
Thanks a lot!

**Comment by gianarb** [comment]
I tagged a new release that contains your changes

https://github.com/profefe/kube-profefe/releases/tag/v0.2.0

Let me know!

**Comment by GTB3NW** [comment]
You're welcome. I'll give this a try soon :)

**Pull request merged**
